BMI_calc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from useraccount.views import login_view, signup_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bmi/', include("bmi.urls")),
    path('user/', include("useraccount.urls")),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bmi/urls.py
from django.urls import path
from bmi.views import bmi_list, bmi_calculate, bmi_delete
app_name = 'bmi'


urlpatterns = [
    path('bmi-list/',bmi_list, name = 'bmi_list'),
    path('bmi-create/',bmi_calculate, name = 'bmi_calculate'),
    path('bmi-delete/<int:id>',bmi_delete, name = 'bmi_delete'),
    # path('product-add/',product_add, name = 'product_add'),
    # #path('product-add/',ProductAddView.as_view(), name = 'product_add'),
    # path('dashboard/',dashboard, name = 'dashboard'),
    # path('product-edit/<int:id>/',product_edit, name = 'product_edit'),
]

useraccount/urls.py
from django.urls import path
from useraccount.views import login_view, signup_view, my_profile, edit_profile, send_suggestion_email,logout_request

app_name = "user"


urlpatterns =[
    path("login/", login_view, name ="login"),
    path("register/", signup_view, name ="register"),
    #path("send-mail/",send_confirm_email, name ="send-mail"),
    path("my-profile/",my_profile, name ="my_profile"),
    path("edit-profile/",edit_profile, name ="edit_profile"),
    path("send-suggestion-email/<int:id>",send_suggestion_email, name ="send_suggestion_email"),
    path("logout/",logout_request, name ="logout"),
]

bmi/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Userdata(models.Model):
    weight = models.FloatField()
    height = models.FloatField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    bmi = models.DecimalField(max_digits=5, decimal_places=2)
    
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    
    
    def __str__(self):
        return f"{self.weight}/{self.height}"


    def save(self, *args, **kwargs):
        self.bmi = self.weight / (self.height * self.height)
        super().save(*args, **kwargs)
        
    
    @property
    def bmi_category(self):
        if self.bmi < 18  :
            return "Underweight"
        elif self.bmi > 18.5 and self.bmi <24.9 :
            return "Normal" 
        elif self.bmi >25 and self.bmi <29.9:
            return "Overwieight"
        else:
            return "Obese"
        
    @property
    def bmi_color(self):
        if self.bmi < 18  :
            return "Orange"
        elif self.bmi > 18.5 and self.bmi <24.9 :
            return "Green" 
        elif self.bmi >25 and self.bmi <29.9:
            return "Blue"
        else:
            return "Red"
    
class Suggestion(models.Model):
    category_choices = (
        ("Underweight","Underweight"),
        ("Normal","Normal"),
        ("Overweight","Overweight"),
        ("Obese","Obese"),
    )
    category = models.CharField(max_length=25, choices=category_choices)
    message = models.TextField()

bmi/forms.py
from django import forms
from bmi.models import Userdata

# # class ProductForm(forms.Form):
# #     name = forms.CharField()
# #     price = forms.CharField()
# #     category = forms.CharField()

class BmiCalculateForm(forms.ModelForm):
    class Meta:
        model = Userdata
        fields =("weight", "height")

bmi/views.py
from django.shortcuts import render,reverse,Http404, get_object_or_404
from django.http import HttpResponseRedirect,HttpResponse
# from bmi.models import Product
# from django.views.generic import CreateView
from django.contrib.auth.decorators import login_required
# #from django.contrib.auth.mixins import LoginRequiredMixin
from bmi.models import Userdata
from bmi.forms import BmiCalculateForm

# # Create your views here.

# def dashboard(request):
#     return render(request, 'dashboard.html')

@login_required(login_url="user:login")
def bmi_list(request):
    bmis = Userdata.objects.filter(user=request.user)
    context = {"bmis": bmis}
    return render(request, 'bmi_list.html',context)

@login_required(login_url="user:login")
def bmi_calculate(request):
    form = BmiCalculateForm(request.POST)
    if form.is_valid():
        user_data = form.save(commit=False)
        user_data.user = request.user
        user_data.save()
        context = {"result": user_data.bmi, "category": user_data.bmi_category, "color": user_data.bmi_color, 'id': user_data.id,  "form": form}
        return render(request,"bmi_calculate.html",context)
    context ={"form":form}
    return render(request,"bmi_calculate.html",context)


@login_required(login_url="user:login")
def bmi_delete(request, *args, **kwargs):
    id = kwargs.get("id", None)
    Userdata.objects.get(id=id).delete()
    return HttpResponseRedirect(reverse("bmi:bmi_list"))
    
# # class ProductAddView(LoginRequiredMixin, CreateView):
# #     model = Product
# #     form_class = ProductForm
# #     template_name ="form.html"
        
# #     def get_success_url(self):
# #         return reverse('product:product_list')

# #     def form_valid(self, form):
# #         product = form.save(commit=False)
# #         product.user = self.request.user
# #         return super().form_valid(product)
#     # 
# @login_required(login_url="user:login")
# def product_add(request):
#     form = ProductForm(request.POST or None, request.FILES or None)
#     #context = {"form":form}
#     # if request.POST:
#     #     print(request.POST)
#     if form.is_valid():
#         # print(form.cleaned_data)
#         #user = request.user # Assignment
#         product = form.save(commit=False)
#         product.user = request.user
#         product.save()
#         #form = ProductForm()
#         #return HttpResponseRedirect("/product/product-list")
#         return HttpResponseRedirect(reverse("product:product_list"))
#     context = {"form":form}
#     return render(request, 'form.html',context)

# def product_edit(request,id):
#     product = get_object_or_404(Product, id=id)
#     form = ProductForm(request.POST or None, request.FILES or None, instance=product)
#     if form_is_valid():
#         form.save()
#         return HttpResponseRedirect(reverse("product:product_list"))
#     context = {"form":form}
#     return render(request,"form.html", context)


# def product_delete(request,id):
#     product = get_object_or_404(Product,id=id)
#     product.delete()
#     return HttpResponseRedirect(reverse("product:product_list"))
    

bmi/templates/bmi_calculate.html
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" name="Calculate" class="btn btn-primary"/></form>

    {% if category %}
    <div>
        BMI: {{result}}
        <div class="{{color}}">{{category}}</div>
    </div>
    <div>
        <a href="{% url 'user:send_suggestion_email' id %}" class="btn btn-primary">Send suggestions</a>
    </div>

    {% endif %}
</form>

<style>
    .Orange{
        color: orange;
    }

    .Normal{
        color: green;
    }
</style>

bmi/templates/bmi_list.html
{% extends 'base.html' %}

{% block navbar %}
    {% include 'components/navbar.html' %}
{% endblock navbar %}
{% block content %}
    <div class="container">
        <div class="d-flex justify-content-between align-items-center">
            <h1>BMI List</h1>
            <div class="text-right">
                <a class="btn btn-primary"  href="{% url 'bmi:bmi_calculate' %}">Calculate my BMI</a>
            </div>
        </div>
        {% if bmis %}
        <table class="table table-striped">
            <tr>
                <th>Height</th>
                <th>Weight</th>
                <th>Index</th>
                <th>Category</th>  
                <th>Action</th> 
            </tr>
            {% for bmi in bmis %}
                <tr>
                    <td>{{bmi.height}}</td>
                    <td>{{bmi.weight}}</td>
                   <td>{{bmi.bmi}} kg/m^2</td>
                    <td>{{bmi.bmi_category}}{{bmi.bmi_color}}</td>
                    <td>
                        <a class="btn btn-danger" href="{% url 'bmi:bmi_delete' bmi.id %}">Delete</a>
                    </td>
                </tr>
            {% endfor %}
    
        </table>
        {% endif %}

        {% if message %}
            <div class="alert alert-success">{{message}}</div>
            <a href="{% url 'bmi:bmi_list' %}">Show all records</a>
        {% endif %}
    </div>
    
{% endblock content %}

bmi/templates/form.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit", name="submit" value="Submit"/>
</form>
 