BMI_calc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from useraccount.views import login_view, signup_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bmi/', include("bmi.urls")),
    path('user/', include("useraccount.urls")),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bmi/urls.py
from django.urls import path
from bmi.views import bmi_list, bmi_calculate, bmi_delete
app_name = 'bmi'


urlpatterns = [
    path('bmi-list/',bmi_list, name = 'bmi_list'),
    path('bmi-create/',bmi_calculate, name = 'bmi_calculate'),
    path('bmi-delete/<int:id>',bmi_delete, name = 'bmi_delete'),
    # path('product-add/',product_add, name = 'product_add'),
    # #path('product-add/',ProductAddView.as_view(), name = 'product_add'),
    # path('dashboard/',dashboard, name = 'dashboard'),
    # path('product-edit/<int:id>/',product_edit, name = 'product_edit'),
]

useraccount/urls.py
from django.urls import path
from useraccount.views import login_view, signup_view, my_profile, edit_profile, send_suggestion_email,logout_request

app_name = "user"


urlpatterns =[
    path("login/", login_view, name ="login"),
    path("register/", signup_view, name ="register"),
    #path("send-mail/",send_confirm_email, name ="send-mail"),
    path("my-profile/",my_profile, name ="my_profile"),
    path("edit-profile/",edit_profile, name ="edit_profile"),
    path("send-suggestion-email/<int:id>",send_suggestion_email, name ="send_suggestion_email"),
    path("logout/",logout_request, name ="logout"),
]

templates/components/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <a class="navbar-brand" href="#">BMI Calculator</a>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'bmi:bmi_list' %}">My BMI</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" tabindex="-1" aria-disabled="true"  href="{% url 'user:my_profile' %}">My Profile</a>
          </li>
        </ul>
        <form class="d-flex" action="/user/logout">
          <button class="btn btn-outline-success" type="submit">Logout</button>
        </form>
      </div>
    </div>
  </nav>